baseURL: 'https://kubeernetes.io/'
languageCode: 'en-us'
title: 'KuBEERnetes.io'
paginate: 5
theme: 'PaperMod'

minify:
  disableXML: true
  minifyOutput: true

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: 'Ku🍺netes.io'
  description: "Casual content around Kubernetes and cloud"
  keywords: [Blog, Kubernetes, Cloud]
  author: "The Kubeernetes team"
  # author: ["Me", "You"] # multiple authors
  # images: ["<link or path of image for opengraph, twitter-cards>"]
  DateFormat: "2006-01-02"
  defaultTheme: auto # dark, light
  disableThemeToggle: false

  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: false
  ShowCodeCopyButtons: false
  ShowWordCount: true
  ShowRssButtonInSectionTermList: true
  UseHugoToc: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: false
  tocopen: false

  assets:
    #  disableHLJS: true # to disable highlight.js
    #  disableFingerprinting: true
    #  favicon: "<link / abs url>"
    #  favicon16x16: "<link / abs url>"
    #  favicon32x32: "<link / abs url>"
    #  apple_touch_icon: "<link / abs url>"
    #  safari_pinned_tab: "<link / abs url>"

    #label:
    #text: "Home"
    #icon: /apple-touch-icon.png
    #iconHeight: 35

  # home-info mode
  homeInfoParams:
    Title: "ku🍺netes.io"
    Content: "Casual stuff about Kubernetes and cloud"

  socialIcons:
    - name: mastodon
      url: "https://que.pasa.co/@kubeernetes"
    - name: instagram
      url: "https://www.instagram.com/kubeernetes/"
    - name: twitch
      url: "https://twitch.tv/kubeernetes"
    - name: github
      url: "https://github.com/capitangolo/kubeernetes-web"

  analytics:
    google:
      SiteVerificationTag: "G-9KFREHKY4X"
        #    bing:
        #      SiteVerificationTag: "XYZabc"
        #    yandex:
        #      SiteVerificationTag: "XYZabc"

  cover:
    hidden: false # hide everywhere but not in structured data
    hiddenInList: false # hide on list pages and home
    hiddenInSingle: false # hide on single page

  editPost:
    URL: ""
    Text: "" # edit text
    appendFilePath: true # to append file path to Edit link

  # for search
  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]
menu:
  main:
    - identifier: categories
      name: categories
      url: /categories/
      weight: 10
    - identifier: tags
      name: tags
      url: /tags/
      weight: 20
# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
pygmentsUseClasses: true
markup:
  highlight:
    noClasses: false
    # anchorLineNos: true
    # codeFences: true
    # guessSyntax: true
    # lineNos: true
    # style: monokai
